const actionNames={
    ADD_CURRENT_USER:"ADD_CURRENT_USER",
    REMOVE_CURRENT_USER:"REMOVE_CURRENT_USER",
    CHANGE_CURRENT_CHAT:"CHANGE_CURRENT_CHAT",
    ADD_MESSAGE:"ADD_MESSAGE"
}

export default actionNames
